
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 19 17:23:48 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 18;
  public static final int GREATER_OR_EQUAL = 38;
  public static final int CONST = 21;
  public static final int EQUALS = 20;
  public static final int BOOL_NOT_EQUAL = 36;
  public static final int NAMESP = 48;
  public static final int GREATER = 37;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 27;
  public static final int NUM_CONST = 17;
  public static final int FOR = 50;
  public static final int LESS = 39;
  public static final int MINUS = 32;
  public static final int STATIC = 49;
  public static final int BOOL_EQUAL = 35;
  public static final int RPAREN = 7;
  public static final int AND = 31;
  public static final int LESS_OR_EQUAL = 40;
  public static final int OR = 30;
  public static final int COMMA = 11;
  public static final int CLASS = 24;
  public static final int INC = 43;
  public static final int DIV = 41;
  public static final int PLUS = 10;
  public static final int ASSIGN = 46;
  public static final int IF = 15;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int MUL = 51;
  public static final int MOD = 42;
  public static final int NUMBER = 14;
  public static final int IDENT = 53;
  public static final int BREAK = 28;
  public static final int VOID = 13;
  public static final int FOREACH = 47;
  public static final int COLON = 45;
  public static final int LBRACE = 3;
  public static final int ELSE = 16;
  public static final int LSQUARE = 22;
  public static final int READ = 26;
  public static final int RSQUARE = 23;
  public static final int WHILE = 29;
  public static final int SCOPE = 52;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 25;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 19;
  public static final int DEC = 44;
  public static final int PRINT = 12;
}

